name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Check Code Style with flake8
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.1.1 flake8-isort==6.1.1

      - name: Run linters
        run: python -m flake8 --extend-exclude .venv,migrations backend

  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        service:
          - { context: ./backend, tag: kittygram_backend }
          - { context: ./frontend, tag: kittygram_frontend }
          - { context: ./nginx, tag: kittygram_gateway }

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service.context }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.tag }}:latest

  deploy:
    name: Deploy to Production
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Debug SSH connection manually
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@${{ secrets.HOST }} echo "✅ SSH OK"

      - name: Copy docker-compose.production.yml via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: "docker-compose.production.yml"
          target: "~/kittygram/"

      - name: Executing remote SSH commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            cd ~/kittygram/
            sudo docker compose -f docker-compose.production.yml pull
            sudo docker compose -f docker-compose.production.yml down
            sudo docker compose -f docker-compose.production.yml up -d

  run_tests:
    name: Run Tests After Deploy
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest

      - name: Run all tests
        run: |
          pytest tests/ --maxfail=5 --disable-warnings

  notify_on_success:
    name: Notify on Success
    needs: run_tests
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Send success message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Deployment of the project ${{ github.repository }} was successful!
            🧑 Author: ${{ github.actor }}
            📝 Commit message: ${{ github.event.commits[0].message }}
            🔗 [Commit link](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
  notify_on_failure:
    name: Notify on Failure
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Send failure message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Deployment of the project ${{ github.repository }} failed!
            🧑 Author: ${{ github.actor }}
            📝 Commit message: ${{ github.event.commits[0].message }}
            🔗 [Commit link](https://github.com/${{ github.repository }}/commit/${{ github.sha }})